[package]
name = "vi-move-game"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.88"

raalog = { path = "../raalog" }
# raalog = { git = "https://github.com/AlexanderARodin/raalog.git", branch = "main" }

ratatui = "0.28.1"
edtui = "0.7.2"

mlua = { version = "0.9.9", features = ["lua54", "vendored"] }
